### PR TITLE
Update tests for the changes of the option names in #122 Part 2

### PR DESCRIPTION
**Pull request by XingerTang**
Updated options are

|Old option name|Updated option name|Old file name|Updated file name|Complete|Issue|
|--|--|--|--|--|--|
|startsnp|start_snp|-|-|√|#108|
|stopsnp|stop_snp|-|-|√|#108|
|out|out_file|-|-|√|#110|
|writekey|out_id_order|-|-|√|#110|
|onlykeyed|out_id_only|-|-|√|#110|
|iothreads|n_io_threads|-|-|√ |#110| 
|runtype|method|-|-|√|#111|
|ncycles|n_cycles|-|-|√|#111|
|maxthreads|n_threads|-|-|√|#111|
|no_params|no_param|-|-|√|#97|
|binary_call_files|binary_call_file|-|-|√|not_implemented| 
|nophasefounders|no_phase_founder|-|-|√|#112|

So far, all the test updates for option name updates proposed in #113 are completed.

### CODE REVIEW

**Comment by gregorgorjanc** [comment]
@XingerTang @AprilYuZhang we need to decide on the plural `n_cycle` and `n_threads` so the tests do the right thing.

**Comment by XingerTang** [comment]
The plurals in the tests are all removed.

**Comment by gregorgorjanc** [comment]
@AprilYuZhang can you have a look at this code from @XingerTang and see if you spot any inconsistencies to give feedback to @XingerTang ?

**Comment by AprilYUZhang** [comment]
> @AprilYUZhang can you have a look at this code from @XingerTang and see if you spot any inconsistencies to give feedback to @XingerTang ?

Temporarily no, but we're talking about the Input (like bfile/plink_file) today. Maybe tomorrow it will be squash and merge.

**Comment by XingerTang** [comment]
@gregorgorjanc Everything is resolved now, can we merge this pull request and see how the tests run?

**Comment by gregorgorjanc** [comment]
> @gregorgorjanc Everything is resolved now, can we merge this pull request and see how the tests run?

Sure. Squash commits and will merge;)

**Comment by XingerTang** [comment]
> > @gregorgorjanc Everything is resolved now, can we merge this pull request and see how the tests run?
> 
> Sure. Squash commits and will merge;)

@gregorgorjanc The squash is done :)

**Comment by gregorgorjanc** [comment]
Merging in.

**Pull request merged**
