### PR TITLE
Update tests for the changes of the option names in #122

### PR DESCRIPTION
**Pull request by XingerTang**
Updated options are:

|Old option name|Updated option name|Old file name|Updated file name|Complete|Issue|
|--|--|--|--|--|--|
|pedigree|ped_file|INPUT FILE|INPUT FILE|√|#109|
|genotypes|geno_file|INPUT FILE|INPUT FILE|√|#109|
|seqfile|seq_file|INPUT FILE|INPUT FILE|√|#109|
|bfile|plink_file|INPUT FILE|INPUT FILE|√|#109|
|mapfile|map_file|INPUT FILE|INPUT FILE|√|#106|
|segmapfile|seg_map_file|INPUT FILE|INPUT FILE|√|#106|
|segfile|seg_file|INPUT FILE|INPUT FILE|√|#106|
|estmaf|est_alt_allele_prob|maf|alt_allele_prob.txt|√|#97,#104|
|error|geno_error_prob|-||√|#97,#102|
|seqerror|seq_error_prob|-|-|√|#97,#102|
|esterrors|est_geno_error_prob|genoError|geno_error_prob.txt|√|#97,#102,#104|
|esterrors|est_seq_error_prob|seqError|seq_error_prob.txt|√|#97,#102,#104|
|-|rec_prob|-|-|√|#97|
|-|est_rec_prob|-|rec_prob.txt|√|#97,#104|
|length|rec_length|-|-|√|#103|
|sexchrom|sex_chrom|-|-|√|#107|

### CODE REVIEW

**Review by gregorgorjanc — COMMENTED** [review]
@XingerTang I reviewed this PR and I think it all looks good!

When should we merge this in given the work of @AprilYUZhang in the other PR at https://github.com/AlphaGenes/AlphaPeel/pull/122?

**Comment by XingerTang** [comment]
> @XingerTang I reviewed this PR and I think it all looks good!
> 
> When should we merge this in given the work of @AprilYUZhang in the other PR at #122?

@gregorgorjanc 
Great! I think you can merge it now as these test updates are for checking the updates at #122. If the test fails after the merge, we can then investigate further what's the reason behind the fails.

**Comment by gregorgorjanc** [comment]
@XingerTang can you squash the commits into one and I merge this in?

**Comment by XingerTang** [comment]
@gregorgorjanc Sure!

**Comment by XingerTang** [comment]
@gregorgorjanc The commits are squashed :)

**Pull request merged**
